---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sonarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      sonarr:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "17"
            envFrom:
              - secretRef:
                  name: sonarr-initdb-secret

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.15.2940@sha256:ca6c735014bdfb04ce043bf1323a068ab1d1228eea5bab8305ca0722df7baf78
            env:
              TZ: America/New_York
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__INSTANCENAME: Sonarr
              SONARR__PORT: 8989
              SONARR__LOG__LEVEL: info
              SONARR__THEME: dark
              # Postgres Setup
              SONARR__POSTGRES__HOST:
                valueFrom:
                  secretKeyRef:
                    name: &pguser sonarr-pguser-secret
                    key: host
              SONARR__POSTGRES__PORT:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: port
              SONARR__POSTGRES__USER:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: user
              SONARR__POSTGRES__PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: password
              SONARR__POSTGRES__MAINDB:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: db
              SONARR__LOG__DBENABLED: "false"
            envFrom:
              - secretRef:
                  name: sonarr-secret

    service:
      app:
        ports:
          http:
            port: &port 8989

    route:
      app:
        hostnames: ["{{ .Release.Name }}.pipitonelabs.com"]
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      media:
        type: nfs
        server: mars.internal
        path: /mnt/user/data/media
      config:
        existingClaim: *app
      scripts:
        type: configMap
        name: sonarr-configmap
        defaultMode: 0775
        globalMounts:
          - path: /scripts/codec-tagger.sh
            subPath: codec-tagger.sh
            readOnly: true
          - path: /scripts/tba-refresher.sh
            subPath: tba-refresher.sh
            readOnly: true
      tmp:
        type: emptyDir