---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app outline
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: outline-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # S3
        AWS_ACCESS_KEY_ID: "{{ .OUTLINE_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .OUTLINE_AWS_SECRET_ACCESS_KEY }}"
        # App
        UTILS_SECRET: "{{ .OUTLINE_UTILS_SECRET }}"
        SECRET_KEY: "{{ .OUTLINE_SECRET_KEY }}"
        OIDC_CLIENT_ID: "{{ .OUTLINE_OAUTH_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OUTLINE_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: *app
    #- extract:
    #    key: minio
