apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-pod
  namespace: default
  labels:
    app: debug-disk
spec:
  selector:
    matchLabels:
      app: debug-disk
  template:
    metadata:
      labels:
        app: debug-disk
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: debug-container
        image: ubuntu:22.04
        command: ["/bin/bash", "-c", "export DEBIAN_FRONTEND=noninteractive; for i in {1..3}; do apt update && apt install -y gdisk parted && break || sleep 5; done && /scripts/clean-disk.sh || { echo 'Script failed, keeping pod alive'; sleep infinity; }"]
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: host-dev
          mountPath: /dev
        - name: script
          mountPath: /scripts
      volumes:
      - name: host-dev
        hostPath:
          path: /dev
      - name: script
        configMap:
          name: disk-clean-script
          defaultMode: 0755
      hostPID: true
      hostIPC: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: disk-clean-script
  namespace: default
data:
  clean-disk.sh: |
    #!/bin/bash
    DISK="/dev/nvme1n1"
    if [ ! -b "$DISK" ]; then
      echo "Error: $DISK not found, exiting to shell"
      sleep infinity
    fi
    # Get disk size in bytes
    DISK_SIZE=$(blockdev --getsize64 $DISK)
    echo "Disk $DISK size: $DISK_SIZE bytes"
    sgdisk --zap-all $DISK || { echo "sgdisk failed"; exit 1; }
    # Define offsets in KB
    OFFSETS=(0 $((1 * 1024**2)) $((10 * 1024**2)) $((100 * 1024**2)) $((1000 * 1024**2)))
    for OFFSET in "${OFFSETS[@]}"; do
      # Convert offset to bytes (since blockdev returns bytes)
      OFFSET_BYTES=$((OFFSET * 1024))
      if [ $OFFSET_BYTES -lt $DISK_SIZE ]; then
        echo "Running dd at offset $OFFSET KB"
        dd if=/dev/zero of="$DISK" bs=1K count=200 oflag=direct,dsync seek=$OFFSET || { echo "dd failed at offset $OFFSET KB"; exit 1; }
      else
        echo "Skipping dd at offset $OFFSET KB (exceeds disk size)"
      fi
    done
    blkdiscard $DISK || { echo "blkdiscard failed"; exit 1; }
    partprobe $DISK || { echo "partprobe failed"; exit 1; }
    echo "Disk cleanup completed, sleeping"
    sleep infinity